#!/bin/bash

while true
do
	sudo /usr/bin/sntp -s au.pool.ntp.org
	while read freq
	do
		if [ -f /home/pi/upconverter ]
		then
			timeout -s SIGINT 15m /home/pi/bin/start-wsprd-upconverter ${freq}
		else
			timeout -s SIGINT 15m /home/pi/bin/start-wsprd ${freq}
		fi
	done < <(shuf /home/pi/frequencies)
done
