#!/bin/bash
date -R 

if [ $# -eq 0 ] ; then
	freq=14.0956
else
	freq=$1
fi

if [ "${freq}" = "$(echo -e "${freq}\n28.8" | sort -g | head -1)" ] ; then
	stream=2
else
	stream=0
fi

rtlsdr_wsprd -f ${freq}M -c VK6FLAB -l OF78WC -d ${stream} -a 1 -S
